### ISSUE TITLE
Binarization creates 2 source files in target workspace

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/ocrd_kraken#16]
While binarizing image to a new workspace two tifs will be created.
The filename of the image is not the filename of the given mets.xml!
It seems the filename of the METS file in the cache directory!?

(source) Files are stored in the root directory of the workspace and looks like this:
`file.path.to.old.workspace.filename`
and
`file.path.to.new.workspace.file.path.to.old.workspace.filename`

The original file (OCR-D-IMG/filename) is missing in the new workspace!
(Inside METS is a reference to the first file mentioned above!)
Steps:

```
ocrd workspace validate
ocrd workspace clone -a -m mets.xml
cd /tmp/pyocrd-'xyz'
ocrd-kraken-binarize -w /new/target/dir
```

**Comment by kba** [comment]
These dot-separated files are the names come from the URL of the thing, e.g. `file:///path/to/old/workspace/filename --> file.path.to.old.workspace.filename`.

Nonetheless, things go wrong, need to debug this with a METS URL.

**Comment by kba** [comment]
https://hackmd.io/LUGofc3iRTekgQKQ7Moa0Q?both#Binarize-all-images-of-a-METS-file

**Comment by kba** [comment]
long out-of-date
