### ISSUE TITLE
Restrict segmentation to print space

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_kraken#22]
If a print space is set via the [corresponding element](https://ocr-d.github.io/gt//pagexml_documentation/pagecontent_xsd_Complex_Type_pc_PageType.html#PageType_PrintSpace) it has to be respected for (block) segmentation.

**Comment by EEngl52** [comment]
@kba @wrznr can this be closed?

**Comment by wrznr** [comment]
No. Open and pressing issue.

**Comment by bertsky** [comment]
Has also been resolved along with #33 – segmenter uses `Workspace.image_from_page` now, which respects the Border annotation.
