### ISSUE TITLE
segmentation: add optional level=region (line segmentation only)

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_kraken#23]
According to the OCR-D functional model, line segmentation takes place after block segmentation. It should therefor check for existing text blocks and restrict its area of operation to them.

**Comment by EEngl52** [comment]
@wrznr @kba can this be closed?

**Comment by wrznr** [comment]
No. Open and pressing issue.

**Comment by bertsky** [comment]
Surprisingly, we did not revisit. Seems more pressing than ever → will look at it.
