### ISSUE TITLE
Complete implementation of OCR with kraken

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_kraken#24]
Text recognition is e.g. referenced in [`ocrd-tool.json`](https://github.com/OCR-D/ocrd_kraken/blob/cae0b9ba441bc212caf8fabbf4a75df337757c76/ocrd_kraken/ocrd-tool.json#L51) but not in [`setup.py`](https://github.com/OCR-D/ocrd_kraken/blob/cae0b9ba441bc212caf8fabbf4a75df337757c76/setup.py#L3).

**Comment by kba** [comment]
Text recognition has since been implemented.
