### ISSUE TITLE
kraken-binarize produces two identical output files per input file

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd_kraken#26]
When calling kraken binarization on a ``mets.xml`` like 
``ocrd process -m mets.xml kraken-binarize -I DEFAULT -O OCR-D-IMG-BIN`` 
I obtain 2 identical binarized images per single input image, one residing in the CWD and another one in a directory ``OCR-D-IMG-BIN``.

Possibly related to #10, #16?

**Comment by mikegerber** [comment]
I believe I only saw this because `ocropy-segment` is littering with copies of its input (can't find the GitHub issue sorry), not from the kraken-binarize before.

At least I don't see the current kraken-binarize littering, but I haven't tested it using `process`.

**Comment by kba** [comment]
From what I can see, this seems not to be the case anymore. The output doesn't have `.png` file extensions which is not ideal but no duplication AFAICS.
