### ISSUE TITLE
 License template not completely filled out

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_kraken#31]
The  [LICENSE](https://github.com/OCR-D/ocrd_kraken/blob/master/LICENSE) does not contain the year and name of the copyright owner:

~~~
   Copyright [yyyy] [name of copyright owner]
~~~

**Comment by bertsky** [comment]
That's not supposed to be changed/customized, actually. You are referring to the **appendix** of the license, which gets [referenced merely as an example](https://github.com/OCR-D/ocrd_kraken/blob/802c6b0b76a3e75070c680aa3b19d36142decf4e/LICENSE#L38). If you do want to use this template, then – according to the [Apache License FAQ](https://www.apache.org/foundation/license-faq.html#Apply-My-Software), this should be done at the top of each source file.
